syntax = "proto3";

package minknow_api.v2.protocol;

option java_package = "com.nanoporetech.minknow_api.v2";
option objc_class_prefix = "MKAPI";
option go_package = "github.com/nanoporetech/minknow_api/go/gen/v2/protocol";

import "minknow_api/acquisition.proto";
import "minknow_api/protocol.proto";
import "google/rpc/status.proto";

service ProtocolsService
{
    // Run a protocol on the connected flow cell.
    //
    // The protocol must be described by a TOML file. The request identifies the
    // protocol and supplies overrides to the default protocol-settings described
    // in the TOML file, in addition it provides user-info for the experiment.
    //
    // This will return an error if one or more of the sub-requests' flow cell identification information is invalid.
    // Otherwise, will return OK, even if any of the sub-requests fail.
    //
    // If a sub-request fails, this will be indicated by the individual response's 'status' field being set.
    rpc begin_protocols(BeginProtocolsRequest) returns (BeginProtocolsResponse) {}

    // Initiates a python instance that runs the script specified by the `path` argument.
    // `list_protocols` will give back a list of protocol scripts that can be started by this call
    //
    // This will return an error if one or more of the sub-requests' flow cell identification information is invalid.
    // Otherwise, will return OK, even if any of the sub-requests fail.
    //
    // If a sub-request fails, this will be indicated by the individual response's 'status' field being set.
    rpc start_protocols(StartProtocolsRequest) returns (StartProtocolsResponse) {}

    // Stops the named protocols.
    //
    // This will return an error if one or more of the sub-requests' run IDs does not correspond to a currently running experiment.
    // Otherwise, will return OK, even if any of the sub-requests fail.
    //
    // If a sub-request fails, this will be indicated by the individual response's 'status' field being set.
    rpc stop_protocols(StopProtocolsRequest) returns (StopProtocolsResponse) {}


    // Gets information about a protocol run.
    //
    // If no run ID is provided, information about the most recently started protocol run is
    // provided.
    //
    // Since 6.5
    rpc get_run_info (minknow_api.protocol.GetRunInfoRequest) returns (minknow_api.protocol.ProtocolRunInfo) {
        option idempotency_level = NO_SIDE_EFFECTS;
    }

    // List previously started protocol run ids (including any current protocol), in order of starting.
    //
    // The returned object can be used to find protocol information with get_run_info.
    //
    // Since 6.5
    rpc list_protocol_runs (minknow_api.protocol.ListProtocolRunsRequest) returns (minknow_api.protocol.ListProtocolRunsResponse) {
        option idempotency_level = NO_SIDE_EFFECTS;
    }

    // Sends out a 'clear history data' request to all flow cells.
    //
    // History data includes protocol protocol info, acquisition info and statistics.
    //
    // Also clears any persistence data that has been written to disk for those protocols which meet the criteria -- this
    // data will not be available after a restart.
    //
    // Does NOT clear experiment results (fast5, fastq, sequencing_summary, etc)
    //
    // Since 6.5
    //
    rpc clear_protocols_history_data(minknow_api.protocol.ClearProtocolHistoryDataRequest) returns (minknow_api.protocol.ClearProtocolHistoryDataResponse) {}

    // Generate a run report and return the report data.
    //
    // If the protocol selected for report generation is already complete the report is a completed report, otherwise
    // the report will be from the in progress protocol.
    //
    // Since 6.5
    rpc generate_run_report(minknow_api.protocol.GenerateRunReportRequest) returns (stream minknow_api.protocol.GenerateRunReportResponse) {}

    // Gets information about a acquisition run.
    //
    // If no run ID is provided, information about the most recently started acquisition run is
    // provided.
    //
    // Since 6.5
    rpc get_acquisition_info (minknow_api.acquisition.GetAcquisitionRunInfoRequest) returns (minknow_api.acquisition.AcquisitionRunInfo) {
        option idempotency_level = NO_SIDE_EFFECTS;
    }

    // List all used protocol group ids used in any previous protocol on the box.
    //
    // Since 6.8
    rpc list_protocol_group_ids(ListGroupIdsRequest) returns (minknow_api.protocol.ListProtocolGroupIdsResponse) {
        option idempotency_level = NO_SIDE_EFFECTS;
    }

}

message BeginProtocolsRequest
{
    message IndividualRequest
    {
        // The position on which to start this protocol.
        string flow_cell_position_name = 1;
        minknow_api.protocol.BeginProtocolRequest settings = 2;
    }

    repeated IndividualRequest requests = 1;
}

message BeginProtocolsResponse
{
    // Represents the response from the proxied call to 'begin_protocol'
    // on a specific flow cell.
    message IndividualResponse
    {
        string flow_cell_position_name = 1;

        oneof payload
        {
            minknow_api.protocol.BeginProtocolResponse response = 2;
            google.rpc.Status status = 3;
        }
    }

    repeated IndividualResponse responses = 1;
}

message StartProtocolsRequest
{
    message IndividualRequest
    {
        // The position on which to start this protocol.
        string flow_cell_position_name = 1;
        minknow_api.protocol.StartProtocolRequest settings = 2;
    }

    repeated IndividualRequest requests = 1;
}

message StartProtocolsResponse
{
    message IndividualResponse
    {
        string flow_cell_position_name = 1;

        oneof payload
        {
            minknow_api.protocol.StartProtocolResponse response = 2;
            google.rpc.Status status = 3;
        }
    }

    repeated IndividualResponse responses = 1;
}

message StopProtocolsRequest
{
    repeated minknow_api.protocol.StopProtocolRequest requests = 1;
}

message StopProtocolsResponse
{
    message IndividualResponse
    {
        string run_id = 1;

        oneof payload
        {
            minknow_api.protocol.StopProtocolResponse response = 2;
            google.rpc.Status status = 3;
        }
    }

    repeated IndividualResponse responses = 1;
}

// Limit the filtering to time-related filters only.
message GroupFilteringInfo {

    minknow_api.protocol.FilteringInfo.TimeFilter experiment_start_time = 1;

    // Default of DESCENDING
    optional minknow_api.protocol.FilteringInfo.OrderDirection order_direction = 2;

    // Filter runs by a specific protocol_group_id
    optional string protocol_group_id = 3;
}

message ListGroupIdsRequest{
    GroupFilteringInfo filter_info = 1;
}
