# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from minknow_api import analysis_workflows_pb2 as minknow__api_dot_analysis__workflows__pb2


class AnalysisWorkflowsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.proxy = channel.unary_stream(
                '/minknow_api.analysis_workflows.AnalysisWorkflowsService/proxy',
                request_serializer=minknow__api_dot_analysis__workflows__pb2.ProxyRequest.SerializeToString,
                response_deserializer=minknow__api_dot_analysis__workflows__pb2.ProxyResponse.FromString,
                )


class AnalysisWorkflowsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def proxy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisWorkflowsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'proxy': grpc.unary_stream_rpc_method_handler(
                    servicer.proxy,
                    request_deserializer=minknow__api_dot_analysis__workflows__pb2.ProxyRequest.FromString,
                    response_serializer=minknow__api_dot_analysis__workflows__pb2.ProxyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'minknow_api.analysis_workflows.AnalysisWorkflowsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnalysisWorkflowsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def proxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/minknow_api.analysis_workflows.AnalysisWorkflowsService/proxy',
            minknow__api_dot_analysis__workflows__pb2.ProxyRequest.SerializeToString,
            minknow__api_dot_analysis__workflows__pb2.ProxyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
