### THIS FILE IS AUTOGENERATED. DO NOT EDIT THIS FILE DIRECTLY ###
import typing
import grpc
from google.protobuf.message import Message
import minknow_api
from minknow_api.debug_pb2_grpc import *
import minknow_api.debug_pb2 as debug_pb2
from minknow_api.debug_pb2 import *
from minknow_api._support import MessageWrapper, ArgumentError
import time
import logging
import sys

__all__ = [
    "DebugService",
    "GetBasecallClientState",
    "GetBasecallClientResponse",
    "GetBasecallServerState",
    "GetBasecallServerResponse",
    "DisconnectFlowCellRequest",
    "DisconnectFlowCellResponse",
    "ConnectFlowCellRequest",
    "ConnectFlowCellResponse",
    "SimulateFrameLossRequest",
    "SimulateFrameLossResponse",
]


def run_with_retry(method: typing.Any, message: Message, timeout: typing.Optional[float], unwraps: list[str], full_name: str) -> MessageWrapper:
    retry_count = 20
    error = None
    for i in range(retry_count):
        try:
            result = MessageWrapper(method(message, timeout=timeout), unwraps=unwraps)
            return result
        except grpc.RpcError as e:
            # Retrying unidentified grpc errors to keep clients from crashing
            retryable_error = (e.code() == grpc.StatusCode.UNKNOWN and "Stream removed" in e.details() or \
                                (e.code() == grpc.StatusCode.INTERNAL and "RST_STREAM" in e.details()))
            if retryable_error:
                logging.info('Bypassed ({}: {}) error for grpc: {}. Attempt {}.'.format(e.code(), e.details(), full_name, i))
            else:
                raise
            error = e
        time.sleep(1)
    raise error


class DebugService(object):
    def __init__(self, channel: grpc.Channel) -> None:
        self._stub = DebugServiceStub(channel)
        self._pb = debug_pb2
        self._full_name = "minknow_api.debug.DebugService"

    
    def get_basecall_clients_states(self, _message: typing.Optional[typing.Union[GetBasecallClientState, MessageWrapper]] = None, _timeout: typing.Optional[float] = None, **kwargs: typing.Any) -> MessageWrapper:
        """Returns the state of the basecall client

        This RPC has no side effects. Calling it will have no effect on the state of the
        system. It is safe to call repeatedly, or to retry on failure, although there is no
        guarantee it will return the same information each time.

        Args:
            _message (minknow_api.debug_pb2.GetBasecallClientState, optional): The message to send.
                This can be passed instead of the keyword arguments.
            _timeout (float, optional): The call will be cancelled after this number of seconds
                if it has not been completed.

        Returns:
            minknow_api.debug_pb2.GetBasecallClientResponse

        Note that the returned messages are actually wrapped in a type that collapses
        submessages for fields marked with ``[rpc_unwrap]``.
        """
        if _message is not None:
            if isinstance(_message, MessageWrapper):
                _message = _message._message
            return run_with_retry(self._stub.get_basecall_clients_states,
                                  _message, _timeout,
                                  [],
                                  self._full_name)

        unused_args = set(kwargs.keys())

        _message = GetBasecallClientState()

        if len(unused_args) > 0:
            raise ArgumentError("Unexpected keyword arguments to get_basecall_clients_states: '{}'".format(", ".join(unused_args)))

        return run_with_retry(self._stub.get_basecall_clients_states,
                              _message, _timeout,
                              [],
                              self._full_name)

    
    def get_basecaller_server_state(self, _message: typing.Optional[typing.Union[GetBasecallServerState, MessageWrapper]] = None, _timeout: typing.Optional[float] = None, **kwargs: typing.Any) -> MessageWrapper:
        """Returns the state of the basecall server

        This RPC has no side effects. Calling it will have no effect on the state of the
        system. It is safe to call repeatedly, or to retry on failure, although there is no
        guarantee it will return the same information each time.

        Args:
            _message (minknow_api.debug_pb2.GetBasecallServerState, optional): The message to send.
                This can be passed instead of the keyword arguments.
            _timeout (float, optional): The call will be cancelled after this number of seconds
                if it has not been completed.

        Returns:
            minknow_api.debug_pb2.GetBasecallServerResponse

        Note that the returned messages are actually wrapped in a type that collapses
        submessages for fields marked with ``[rpc_unwrap]``.
        """
        if _message is not None:
            if isinstance(_message, MessageWrapper):
                _message = _message._message
            return run_with_retry(self._stub.get_basecaller_server_state,
                                  _message, _timeout,
                                  [],
                                  self._full_name)

        unused_args = set(kwargs.keys())

        _message = GetBasecallServerState()

        if len(unused_args) > 0:
            raise ArgumentError("Unexpected keyword arguments to get_basecaller_server_state: '{}'".format(", ".join(unused_args)))

        return run_with_retry(self._stub.get_basecaller_server_state,
                              _message, _timeout,
                              [],
                              self._full_name)

    
    def disconnect_flow_cell(self, _message: typing.Optional[typing.Union[DisconnectFlowCellRequest, MessageWrapper]] = None, _timeout: typing.Optional[float] = None, **kwargs: typing.Any) -> MessageWrapper:
        """Disconnect flow cell at a simulated position
        Preconditions:
        - the position is a simulated position
        The call is ignored if the flow cell at that position is already disconnected

        Args:
            _message (minknow_api.debug_pb2.DisconnectFlowCellRequest, optional): The message to send.
                This can be passed instead of the keyword arguments.
            _timeout (float, optional): The call will be cancelled after this number of seconds
                if it has not been completed.

        Returns:
            minknow_api.debug_pb2.DisconnectFlowCellResponse

        Note that the returned messages are actually wrapped in a type that collapses
        submessages for fields marked with ``[rpc_unwrap]``.
        """
        if _message is not None:
            if isinstance(_message, MessageWrapper):
                _message = _message._message
            return run_with_retry(self._stub.disconnect_flow_cell,
                                  _message, _timeout,
                                  [],
                                  self._full_name)

        unused_args = set(kwargs.keys())

        _message = DisconnectFlowCellRequest()

        if len(unused_args) > 0:
            raise ArgumentError("Unexpected keyword arguments to disconnect_flow_cell: '{}'".format(", ".join(unused_args)))

        return run_with_retry(self._stub.disconnect_flow_cell,
                              _message, _timeout,
                              [],
                              self._full_name)

    
    def connect_flow_cell(self, _message: typing.Optional[typing.Union[ConnectFlowCellRequest, MessageWrapper]] = None, _timeout: typing.Optional[float] = None, **kwargs: typing.Any) -> MessageWrapper:
        """Connect flow cell at a simulated position
        Preconditions:
        - the position is a simulated position
        The call is ignored if the position already has a flow cell connected

        Args:
            _message (minknow_api.debug_pb2.ConnectFlowCellRequest, optional): The message to send.
                This can be passed instead of the keyword arguments.
            _timeout (float, optional): The call will be cancelled after this number of seconds
                if it has not been completed.
            flow_cell_id (str, optional): The unique identifier for the flow cell.

                This should be same as the value printed onto the flow cell casing. Not all flow cells will
                have the flow cell ID recorded in a way that MinKNOW can read. In those cases, this will be an
                empty string, even though the user may be able to see a printed identifier on the flow cell.
            product_code (str, optional): The product code for the flow cell.

                This should be the code displayed in the shop where the flow cell was bought. Not all
                flow cells will have the product code recorded in a way that MinKNOW can read. In those cases,
                this will be an empty string.
            asic_id_str (str, optional): The unique identifier for the ASIC (formatted as string).

                This is a value uniquely identifying the ASIC embedded in the flow cell. It will
                always be set when a flow cell is present.
            adapter_id (str, optional): The unique identifier of an attached flongle adapter.

                If set then the simulated device will assume an adapter is present.
                This is ignored if not a Simulated MinION
            use_count (int, optional): The use count for this flow cell.

                Can be set to mimic a flow cell being inserted that has exceeded the use count limit.
            flow_cell_partner (str, optional): The partner the flow cell was produced for.

        Returns:
            minknow_api.debug_pb2.ConnectFlowCellResponse

        Note that the returned messages are actually wrapped in a type that collapses
        submessages for fields marked with ``[rpc_unwrap]``.
        """
        if _message is not None:
            if isinstance(_message, MessageWrapper):
                _message = _message._message
            return run_with_retry(self._stub.connect_flow_cell,
                                  _message, _timeout,
                                  [],
                                  self._full_name)

        unused_args = set(kwargs.keys())

        _message = ConnectFlowCellRequest()

        if "flow_cell_id" in kwargs:
            unused_args.remove("flow_cell_id")
            _message.flow_cell_id = kwargs['flow_cell_id']

        if "product_code" in kwargs:
            unused_args.remove("product_code")
            _message.product_code = kwargs['product_code']

        if "asic_id_str" in kwargs:
            unused_args.remove("asic_id_str")
            _message.asic_id_str = kwargs['asic_id_str']

        if "adapter_id" in kwargs:
            unused_args.remove("adapter_id")
            _message.adapter_id = kwargs['adapter_id']

        if "use_count" in kwargs:
            unused_args.remove("use_count")
            _message.use_count = kwargs['use_count']

        if "flow_cell_partner" in kwargs:
            unused_args.remove("flow_cell_partner")
            _message.flow_cell_partner = kwargs['flow_cell_partner']

        if len(unused_args) > 0:
            raise ArgumentError("Unexpected keyword arguments to connect_flow_cell: '{}'".format(", ".join(unused_args)))

        return run_with_retry(self._stub.connect_flow_cell,
                              _message, _timeout,
                              [],
                              self._full_name)

    
    def simulate_frame_loss(self, _message: typing.Optional[typing.Union[SimulateFrameLossRequest, MessageWrapper]] = None, _timeout: typing.Optional[float] = None, **kwargs: typing.Any) -> MessageWrapper:
        """Simulate frame loss for a specified amount of time
        The request will only trigger the frame loss once during
        the next initiated acquisition.
        Preconditions:
        - The position must be a simulated position
        - An acquisition must not already be in progress

        Args:
            _message (minknow_api.debug_pb2.SimulateFrameLossRequest, optional): The message to send.
                This can be passed instead of the keyword arguments.
            _timeout (float, optional): The call will be cancelled after this number of seconds
                if it has not been completed.
            frame_loss_duration (google.protobuf.duration_pb2.Duration, optional): The duration for which the frame loss will occur.
            start_frame (int, optional): The frame index from which the frame loss will begin

                For simulated PromethIONs this equates to the frame index within a section
            start_section (int, optional): Optional section index from which the frame loss will begin

                For simulated PromethIONs a section equates to a completed scatterlist
            repeats (int, optional): Optional number of times to repeat the failed transfers

                This will reset the frame loss on starting a new acquisition or
                resuming acquisition on an existing signal reader.

        Returns:
            minknow_api.debug_pb2.SimulateFrameLossResponse

        Note that the returned messages are actually wrapped in a type that collapses
        submessages for fields marked with ``[rpc_unwrap]``.
        """
        if _message is not None:
            if isinstance(_message, MessageWrapper):
                _message = _message._message
            return run_with_retry(self._stub.simulate_frame_loss,
                                  _message, _timeout,
                                  [],
                                  self._full_name)

        unused_args = set(kwargs.keys())

        _message = SimulateFrameLossRequest()

        if "frame_loss_duration" in kwargs:
            unused_args.remove("frame_loss_duration")
            _message.frame_loss_duration.CopyFrom(kwargs['frame_loss_duration'])

        if "start_frame" in kwargs:
            unused_args.remove("start_frame")
            _message.start_frame = kwargs['start_frame']

        if "start_section" in kwargs:
            unused_args.remove("start_section")
            _message.start_section = kwargs['start_section']

        if "repeats" in kwargs:
            unused_args.remove("repeats")
            _message.repeats = kwargs['repeats']

        if len(unused_args) > 0:
            raise ArgumentError("Unexpected keyword arguments to simulate_frame_loss: '{}'".format(", ".join(unused_args)))

        return run_with_retry(self._stub.simulate_frame_loss,
                              _message, _timeout,
                              [],
                              self._full_name)
